---
abstract: 'Object interfaces to lists with useful methods'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-Objects-WithUtils
requires:
  Carp: 0
  Exporter: 0
  List::MoreUtils: 0.33
  List::Util: 0
  List::UtilsBy: 0.09
  Module::Runtime: 0.013
  Role::Tiny: 1
  Scalar::Util: 0
  Storable: 0
  autobox: 0
  parent: 0
  perl: v5.8.9
  strictures: 1
resources:
  repository: git://github.com/avenj/list-objects-withutils.git
version: 1.004000
