---
abstract: 'List objects, kitchen sink included'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-Objects-WithUtils
recommends:
  List::UtilsBy::XS: 0.03
  Type::Tiny: 0.022
requires:
  Carp: 0
  Class::Method::Modifiers: 0
  Exporter: 0
  List::MoreUtils: 0.33
  List::Util: 1.32
  List::UtilsBy: 0.09
  Module::Runtime: 0.013
  Role::Tiny: 1.003
  Scalar::Util: 0
  Type::Tie: 0.004
  autobox: 0
  overload: 0
  parent: 0
  strictures: 1
resources:
  repository: git://github.com/avenj/list-objects-withutils.git
version: 2.009001
