---
abstract: 'List objects, kitchen sink included'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.023, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: List-Objects-WithUtils
recommends:
  List::UtilsBy::XS: 0.03
requires:
  Class::Method::Modifiers: 0
  Exporter: 0
  List::UtilsBy: 0.09
  Module::Runtime: 0.013
  Role::Tiny: 1.003
  Type::Tie: 0.004
  Type::Tiny: 0
  parent: 0
  strictures: 1
resources:
  repository: git://github.com/avenj/list-objects-withutils.git
version: 2.017001
